version: '3'

services:
  back-end:
    build: .
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  test:
    build: 
      context: .
      dockerfile: Dockerfile-test
    volumes:
      - .:/app
    stdin_open: true
    depends_on:
      - back-end
  db:
      image: postgres:15-alpine
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      expose:
        - 5432
      environment:
        - POSTGRES_USER=be_service
        - POSTGRES_PASSWORD=qwerty@123
        - POSTGRES_DB=e_commerce_db

volumes:
      postgres_data: 