FROM python:3.8

WORKDIR /dist

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./app/requirement.txt /dist/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /dist/requirements.txt

COPY . /dist

ENV PYTHONPATH="${PYTHONPATH}:/dist/app"